Repository buildly-release-management/buildly-react-template, pull requests merged in 2022-09, with the labels that each got.

#170 Remove stripe and add email verification
  initialize_container.sh
  package.json
  src/App.js
  src/components/StripeCard/StripeCard.js
  src/index.js
  src/pages/MissingData/MissingData.js
  src/pages/Register/Register.js
  src/pages/VerifyEmail/VerifyEmail.js
  src/redux/authuser/actions/authuser.actions.js
  src/redux/authuser/actions/authuser.actions.test.js
  src/redux/authuser/reducers/authuser.reducer.js
  src/redux/authuser/reducers/authuser.reducer.test.js
  src/redux/authuser/sagas/authuser.saga.js
  src/routes/routesConstants.js
Labels: enhancement

#171 Theme changes
  src/components/Copyright/Copyright.js
  src/components/Copyright/Services.js
  src/components/Copyright/Support.js
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/InlineEditor/InlineEditor.js
  src/components/Modal/ConfirmModal.js
  src/components/Modal/FormModal.js
  src/layout/TopBar/TopBar.js
  src/pages/Dashboard/components/Kanban.js
  src/pages/Dashboard/components/List.js
  src/pages/Dashboard/components/UserDashboard.js
  src/pages/Dashboard/forms/AddFeatures.js
  src/pages/Dashboard/forms/DescribeProcess.js
  src/pages/Dashboard/forms/DropColumn.js
  src/pages/Dashboard/forms/IssueSuggestions.js
  src/pages/Dashboard/forms/NewFeatureForm.js
  src/pages/DeveloperForm/DeveloperForm.js
  src/pages/ForgotPassword/ForgotPassword.js
  src/pages/Help/Help.js
  src/pages/Login/Login.js
  src/pages/NewProduct/NewProduct.js
  src/pages/NewProduct/components/ApplicationMarket.js
  src/pages/NewProduct/components/BudgetTechnology.js
  src/pages/NewProduct/components/MinimalFunctionality.js
  src/pages/NewProduct/components/ProductSetup.js
  src/pages/NewProduct/components/TeamUser.js
  src/pages/NewProduct/components/UseInfo.js
  src/pages/Products/Products.js
  src/pages/Register/Register.js
  src/pages/ResetPassword/ResetPassword.js
  src/pages/TicketStatus/TicketStatus.js
  src/pages/UserManagement/UserGroups/UserGroups.js
  src/pages/UserManagement/UserManagement.js
  src/pages/UserManagement/Users/Users.js
  src/styles/theme.js
Labels: enhancement

#173 Fixes from feedback 09/29
  src/layout/TopBar/TopBar.js
  src/pages/Dashboard/components/Kanban.js
  src/pages/Dashboard/components/List.js
  src/pages/Dashboard/forms/DescribeProcess.js
  src/pages/NewProduct/ProductFormConstants.js
  src/pages/NewProduct/components/ApplicationMarket.js
  src/pages/NewProduct/components/ProductSetup.js
Labels: bug, enhancement

#159 add docs & show list on the UI
  src/pages/NewProduct/ProductFormConstants.js
  src/pages/NewProduct/components/ApplicationMarket.js
  src/pages/NewProduct/components/BudgetTechnology.js
  src/pages/NewProduct/components/TeamUser.js
  src/pages/NewProduct/components/UseInfo.js
  src/redux/product/actions/product.actions.js
  src/redux/product/actions/product.actions.test.js
  src/redux/product/reducers/product.reducer.js
  src/redux/product/reducers/product.reducer.test.js
  src/redux/product/sagas/product.saga.js
Labels: enhancement

#67 show static representation of tickets in graph format
  package.json
  src/pages/Dashboard/components/BarChart.js
  src/pages/Dashboard/components/UserDashboard.js
Labels: enhancement, on-hold
