Repository buildly-release-management/buildly-react-template, pull requests merged in 2024-04, with the labels that each got.

#274 Fix/issues
  .eslintrc.json
  .github/ISSUE_TEMPLATE.md
  src/components/Button/Button.tsx
  src/components/Chatbot/Chatbot.js
  src/components/ReleaseModal/Modal.tsx
  src/layout/TopBar/TopBar.js
  src/modules/release/components/QuickForm/QuickForm.css
  src/modules/release/components/QuickForm/QuickForm.tsx
  src/modules/release/details/ReleaseDetails.tsx
  src/modules/release/details/components/ReleaseForm.tsx
  src/modules/release/list/ReleaseList.tsx
  src/pages/ForgotPassword/ForgotPassword.js
  src/pages/Login/Login.js
  src/pages/NewProduct/NewProduct.js
  src/pages/NewProduct/components/ApplicationMarket.js
  src/pages/NewProduct/components/BudgetTechnology.js
  src/pages/NewProduct/components/ProductSetup.js
  src/pages/NewProduct/components/Setup.js
  src/pages/NewProduct/components/TeamUser.js
  src/pages/NewProduct/components/UseInfo.js
  src/pages/Register/Register.js
  src/pages/ResetPassword/ResetPassword.js
  src/pages/Roadmap/Roadmap.js
  src/pages/Roadmap/components/Kanban.js
  src/pages/Roadmap/components/Report/Report.js
  src/pages/Roadmap/components/Tabular.js
  src/pages/Roadmap/forms/AddIssues.js
  src/pages/Roadmap/forms/ShowRelatedIssues.js
  src/pages/UserManagement/UserManagement.js
  src/pages/UserProfile/EditUserProfile/EditUserProfile.js
  src/pages/UserProfile/Subscriptions/Subscriptions.js
  src/redux/googleSheet/sagas/googleSheet.saga.js
  src/redux/product/sagas/product.saga.js
  src/utils/validators.js
  yarn-error.log
Labels: bug, enhancement

#280 Production release
  .eslintrc.json
  .github/ISSUE_TEMPLATE.md
  .github/workflows/dev-build.yml
  .github/workflows/prod-build.yml
  package.json
  src/components/Button/Button.tsx
  src/components/Chatbot/Chatbot.js
  src/components/ReleaseModal/Modal.tsx
  src/layout/TopBar/TopBar.js
  src/modules/release/components/QuickForm/QuickForm.css
  src/modules/release/components/QuickForm/QuickForm.tsx
  src/modules/release/details/ReleaseDetails.tsx
  src/modules/release/details/components/ReleaseForm.tsx
  src/modules/release/list/ReleaseList.tsx
  src/pages/ForgotPassword/ForgotPassword.js
  src/pages/Login/Login.js
  src/pages/NewProduct/NewProduct.js
  src/pages/NewProduct/components/ApplicationMarket.js
  src/pages/NewProduct/components/BudgetTechnology.js
  src/pages/NewProduct/components/ProductSetup.js
  src/pages/NewProduct/components/Setup.js
  src/pages/NewProduct/components/TeamUser.js
  src/pages/NewProduct/components/UseInfo.js
  src/pages/Register/Register.js
  src/pages/ResetPassword/ResetPassword.js
  src/pages/Roadmap/Roadmap.js
  src/pages/Roadmap/components/Kanban.js
  src/pages/Roadmap/components/Report/Report.js
  src/pages/Roadmap/components/Tabular.js
  src/pages/Roadmap/forms/AddIssues.js
  src/pages/Roadmap/forms/IssueSuggestions.js
  src/pages/Roadmap/forms/ShowRelatedIssues.js
  src/pages/UserManagement/UserManagement.js
  src/pages/UserProfile/EditUserProfile/EditUserProfile.js
  src/pages/UserProfile/Subscriptions/Subscriptions.js
  src/redux/googleSheet/sagas/googleSheet.saga.js
  src/redux/product/sagas/product.saga.js
  src/utils/validators.js
  yarn-error.log
Labels: Deployment

#281 Production release v0.7.0
  .github/workflows/prod-build.yml
  package.json
Labels: Deployment

#279 Commenter user info added - #278
  src/pages/Roadmap/forms/Comments.js
  src/redux/release/sagas/release.saga.js
Labels: bug
